os: osx
osx_image: xcode13.1
language: swift
script:
-xcodebuild clean build test -project EssestialFeeds.xcodeproj -scheme "CI_MacOS" CODE_SIGN_IDENTITY="" CODE_SIGN_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
-xcodebuild clean build test -project EssestialFeeds.xcodeproj -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGN_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=12.2,name=iphone 8" ONLY_ACTIVE_ARCH=YES
